### PR TITLE
fix: gc

### LINKED ISSUE #627: The value of "val" is out of range.
Hello,

I've been seeing some intermittent failures with this error.

```
The value of "val" is out of range. It must be a safe integer greater than 0. Received 0
```

Based on the stack trace it's coming from here.

https://github.com/dnlup/doc/blob/next/lib/gc.js#L71

The code I have that should be throwing the error is simplified here.

```
const doc = require('@dnlup/doc');

const sampler = doc({
  collect: {
    gc: true,
    cpu: false,
    memory: false,
    resourceUsage: false,
    eventLoopDelay: false,
    eventLoopUtilization: false,
    activeHandles: false,
  },
});

sampler.on('sample', () => {
  // Other functionality here
});
```

Is there something on my end that could be wrong and causing this error to be thrown intermittently? It's not easily reproducible.

Thank you.

### PR DESCRIPTION
**Pull request by dnlup**
Fix "the-value-of-val-is-out-of-range" error.

Closes #627 .

### CODE REVIEW

File: lib/gc.js [hunk 1]
```diff
@@ -64,11 +64,14 @@ class GCEntry {
   [kSample] (ns) {
     this[kTotalDuration] += ns
     /**
-     * We have to truncate the value here because `record`
+     * We have to adjust the value here because `record`
      * only accepts integer values:
      * https://github.com/nodejs/node/blob/cdad3d8fe5f468aec6549fd59db73a3bfe063e3c/lib/internal/histogram.js#L283-L284
      */
-    this[kHistogram].record(Math.trunc(ns))
+    const val = Math.floor(ns)
```
Comment (dnlup) [inline lib/gc.js]: @andrewpuch Here we don't truncate anymore, but didn't see any difference, do you see any issues with it?

Comment (dnlup) [reply lib/gc.js]: Sorry, there's `round` not `floor` I have forced pushed.

**Comment by andrewpuch** [comment]
LGTM
